### ISSUE TITLE
Fix circles tool linked to email instead of 3botname

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/taiga-contrib-threefold-auth#1]
Right now if you log in with TF connect the account is linked to your email address instead of your TF connect username. If you change email you can't login anymore. Email in TF connect is an information field, not an identifier for authentication. Your login ID should be linked to your TF connect username

- [ ] Fix for new users
- [ ] Be sure current users are linked to their username (can be on next login) instead of existing email address 

Should be doable since the Circles tool doesn't use the email address but a hash based on it to do authentication. Changing your email address in your profile has no effect on your login procedure.

**Comment by hossnys** [comment]
@sabrinasadik it's something related to changing the login procedure which is totally related to development team

**Comment by xmonader** [comment]
@sameh-farouk can you please take a look at this, what will be affected if we do that too

**Comment by sameh-farouk** [comment]
@jdelrue please provide more details about **how to reproduce**. I changed my registered email in Tiaga profile, so it does not match with the email in my TF connect app, and still can log in normally.

implementation-wise in [taiga-contrib-threefold-auth](https://github.com/threefoldtech/taiga-contrib-threefold-auth/tree/main) it will link the Tiaga user account to the username used by the threefold account. it is searching for a match in AuthData model instances by the stored 3bot username, not the stored email address.

https://github.com/threefoldtech/taiga-contrib-threefold-auth/blob/cc23d1331e74aad8150c037ddccc0e7917d66a14/back/taiga_contrib_threefold_auth/services.py#L38

so (per implementation) if you changed your email address this should not cause any issues in the authentication process. if it does, and if we are able to reproduce then it's a bug somewhere that we indeed need to investigate.

**Comment by hossnys** [comment]
the login procedure in the new taiga login-plugin is working depending on username and as early registered users was registered with some flags belong to the old taiga login procedure so if they changed there mail in threefold connect app the taiga will treat them as new users and create new account for them as they appear coming from new login provider than the old flag in DB for them , but if we delete this flag from DB which is stored in users_authdata table , this will enable them to login to there old accounts but using same email , for the newly created users it doesn't matter if you changed email several times as the login depend on username which is your account name in threefold connect app .

**Comment by hossnys** [comment]
so closing this as it was an migration issue, not an implementation issue. And was fixed by manipulating the DB
